name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  healthcheck:
    name: 'Mild Blue Health Check'
    runs-on: ubuntu-latest
    steps:
      - name: Check health
        run: curl -f "https://mildblue.slp.blue/healthz"
