name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:     
  healthcheck:
    name: 'Mild Blue Health Check'
    runs-on: ubuntu-latest
    steps:        
      - name: Check health
        id: healthcheck
        uses: actions/github-script@v5
        with:
          script: |
            const core = require('@actions/core');
            const http = require('@actions/http-client');

            async function run() {
              const httpClient = new http.HttpClient('healthcheck');
              const response = await httpClient.get('https://mildblue.slp.blue/healthz');
              if (response.message.statusCode != 200) {
                core.setFailed('Health check failed');
              }
            }

            run();
