name: Production release
# Releases new docker images and redeploys all AWS ECS services

on:
  workflow_dispatch:

jobs:     
  healthcheck:
    name: 'Mild Blue Health Check'
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 60 seconds
        run: sleep 60
        
      - name: Check health
        id: healthcheck
        uses: actions/github-script@v5
        with:
          script: |
            const core = require('@actions/core');
            const http = require('@actions/http-client');
            const httpClient = new http.HttpClient('healthcheck');
            const response = await httpClient.get('https://mildblue.slp.blue/healthz');
            if (response.message.statusCode != 200) {
              core.setFailed('Health check failed');
            }
